autostart="dwmblocks synergys"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1
xautolock -time 5 -cornerdelay 1 -corners 00+0 -locker slock&
exec /usr/local/bin/startdwm
